### PR TITLE
Swapped from Docker to composite.

### PR DESCRIPTION
**Pull request by WildCard65**
This speeds up the action by skipping the required Docker build.
I also added an input so consumers can specify where yapf should be executed.

### CODE REVIEW

**Comment by AlexanderMelde** [comment]
Awesome addition! Thank you very much, this is looking good!

**Comment by AlexanderMelde** [comment]
Hello @WildCard65, to me it looks like the code you provided doesnt work yet, i will undo the merge.

This is the log i get when i do a run:

```
Collecting yapf
  Downloading https://files.pythonhosted.org/packages/c1/5d/d84677fe852bc5e091739acda444a9b6700ffc6b11a21b00dd244c8caef0/yapf-0.30.0-py2.py3-none-any.whl (190kB)
Installing collected packages: yapf
Successfully installed yapf-0.30.0
/home/runner/work/_temp/b17fbc7c-f2a8-44c1-bdd7-d1d6f117341e.sh: line 1: yapf: command not found
##[error]Process completed with exit code 127.
```

i tested using 
```
name: YAPF Formatting Check
on: [push]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run YAPF to test if python code is correctly formatted.
      uses: AlexanderMelde/yapf-action@master
      with:
        yapf-args: --verbose
```
(added yapf-args as additional input, but this should not hinder yapf from being found.

**Comment by WildCard65** [comment]
It worked for me... How odd.

**Comment by WildCard65** [comment]
@AlexanderMelde Wait, your test script doesn't use ```actions/setup-python```
This action configures the Path environment variable required for both system and user installed packages.

**Comment by AlexanderMelde** [comment]
@WildCard65  Can you provide me the test script you used? :)

**Comment by WildCard65** [comment]
https://github.com/WildCard65/ambuild/blob/final_autover/.github/workflows/yapf.yml

**Pull request merged**
